repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: api/black
        name: API black
        language: system
        entry: bash -c 'cd api && docker compose run --rm --no-TTY --no-deps --entrypoint "black --check ." django'
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.1
    hooks:
    -    id: ruff
         name: API ruff
         language: system
         entry: bash -c 'cd api && docker compose run --rm --no-TTY --no-deps --entrypoint "ruff check ." django'
