# Generated by Django 4.2.5 on 2023-09-18 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("name", models.CharField(max_length=127)),
                ("code", models.CharField(max_length=127)),
                ("group", models.CharField(max_length=127)),
                ("description", models.CharField(max_length=127)),
                ("image", models.ImageField(upload_to="img", verbose_name="Image")),
                ("quantity_in_stock", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tags", models.ManyToManyField(to="products.tag")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
