# Generated by Django 4.2.5 on 2023-09-18 14:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0002_productphoto_producttag_product_photocode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=5)),
                ("status", models.CharField(max_length=127)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("quantity", models.IntegerField()),
                ("price_at_order_time", models.DecimalField(decimal_places=2, max_digits=5)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=5)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orders.order")),
                ("product", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="products.product")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
