# Generated by Django 4.2.5 on 2023-09-18 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="users.user"),
        ),
    ]
