name: Django run tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up docker-compose
      uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: '2.14.2'
    - name: Check docker-compose version
      run: |
        docker-compose --version
    - name: Build docker
      run: |
        docker network create anri_main
        cd api && docker-compose build
    - name: Run Tests
      run: |
        cd api && docker-compose run django pytest
